using System.Collections.Generic;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Models;

namespace NeowCompanions.NeowCompanionsCode.Models;

public sealed class NeowCompanionRelicPool : CustomRelicPoolModel
{
    public override bool IsShared => true;

    public override bool SeenByDefault => true;

    protected override IEnumerable<RelicModel> GenerateAllRelics()
    {
        return
        [
            ModelDb.Relic<SoulFyshPipRelic>(),
            ModelDb.Relic<WrigglerRelic>(),
            ModelDb.Relic<CeremonialBeastRelic>(),
            ModelDb.Relic<KinFollowerRelic>(),
            ModelDb.Relic<EyeWithTeethRelic>(),
            ModelDb.Relic<GremlinMercRelic>(),
            ModelDb.Relic<ThievingHopperRelic>(),
            ModelDb.Relic<AeonglassRelic>(),
            ModelDb.Relic<LagavulinMatriarchRelic>(),
            ModelDb.Relic<TheKinRelic>(),
            ModelDb.Relic<WaterfallGiantRelic>(),
            ModelDb.Relic<VantomRelic>(),
            ModelDb.Relic<KnowledgeDemonRelic>(),
            ModelDb.Relic<TheInsatiableRelic>(),
            ModelDb.Relic<QueenRelic>(),
            ModelDb.Relic<TestSubjectRelic>(),
            ModelDb.Relic<SeapunkRelic>(),
            ModelDb.Relic<ShrinkerBeetleRelic>(),
            ModelDb.Relic<OperosisRelic>(),
            ModelDb.Relic<ArchitectRelic>(),
            ModelDb.Relic<RustcladRelic>(),
            ModelDb.Relic<ShadeleafRelic>(),
            ModelDb.Relic<GlitchlingRelic>(),
            ModelDb.Relic<BonebinderRelic>(),
            ModelDb.Relic<GildedPageRelic>(),
            ModelDb.Relic<EmberPipRelic>(),
            ModelDb.Relic<FrostPipRelic>(),
            ModelDb.Relic<StormPipRelic>(),
            ModelDb.Relic<ThornPipRelic>(),
            ModelDb.Relic<KaiserCrabRelic>(),
            ModelDb.Relic<BygoneEffigyRelic>(),
            ModelDb.Relic<ByrdonisRelic>(),
            ModelDb.Relic<PhrogParasiteRelic>(),
            ModelDb.Relic<SkulkingColonyRelic>(),
            ModelDb.Relic<PhantasmalGardenerRelic>(),
            ModelDb.Relic<TerrorEelRelic>(),
            ModelDb.Relic<DecimillipedeRelic>(),
            ModelDb.Relic<EntomancerRelic>(),
            ModelDb.Relic<InfestedPrismRelic>(),
            ModelDb.Relic<KnightGangRelic>(),
            ModelDb.Relic<MechaKnightRelic>(),
            ModelDb.Relic<SoulNexusRelic>(),
            ModelDb.Relic<AssassinRubyRaiderRelic>(),
            ModelDb.Relic<AxeRubyRaiderRelic>(),
            ModelDb.Relic<BruteRubyRaiderRelic>(),
            ModelDb.Relic<CrossbowRubyRaiderRelic>(),
            ModelDb.Relic<FlyconidRelic>(),
            ModelDb.Relic<FogmogRelic>(),
            ModelDb.Relic<MawlerRelic>(),
            ModelDb.Relic<FuzzyWurmCrawlerRelic>(),
            ModelDb.Relic<InkletRelic>(),
            ModelDb.Relic<SnappingJaxfruitRelic>(),
            ModelDb.Relic<SlitheringStranglerRelic>(),
            ModelDb.Relic<LeafSlimeSRelic>(),
            ModelDb.Relic<LeafSlimeMRelic>(),
            ModelDb.Relic<TwigSlimeSRelic>(),
            ModelDb.Relic<TwigSlimeMRelic>(),
            ModelDb.Relic<VineShamblerRelic>(),
            ModelDb.Relic<ChomperRelic>(),
            ModelDb.Relic<CubexConstructRelic>(),
            ModelDb.Relic<DampCultistRelic>(),
            ModelDb.Relic<CalcifiedCultistRelic>(),
            ModelDb.Relic<CorpseSlugRelic>(),
            ModelDb.Relic<TwoTailedRatRelic>(),
            ModelDb.Relic<SewerClamRelic>(),
            ModelDb.Relic<HauntedShipRelic>(),
            ModelDb.Relic<SludgeSpinnerRelic>(),
            ModelDb.Relic<PunchConstructRelic>(),
            ModelDb.Relic<FossilStalkerRelic>(),
            ModelDb.Relic<LivingFogRelic>(),
            ModelDb.Relic<ParafrightRelic>(),
            ModelDb.Relic<TunnelerRelic>(),
            ModelDb.Relic<SpinyToadRelic>(),
            ModelDb.Relic<StabbotRelic>(),
            ModelDb.Relic<HunterKillerRelic>(),
            ModelDb.Relic<TorchHeadAmalgamRelic>(),
            ModelDb.Relic<BowlbugEggRelic>(),
            ModelDb.Relic<BowlbugNectarRelic>(),
            ModelDb.Relic<BowlbugRockRelic>(),
            ModelDb.Relic<BowlbugSilkRelic>(),
            ModelDb.Relic<LouseProgenitorRelic>(),
            ModelDb.Relic<SlumberingBeetleRelic>(),
            ModelDb.Relic<AxebotRelic>(), ModelDb.Relic<BattleFriendV1Relic>(), ModelDb.Relic<BattleFriendV2Relic>(), ModelDb.Relic<BattleFriendV3Relic>(),
            ModelDb.Relic<DevotedSculptorRelic>(), ModelDb.Relic<ExoskeletonRelic>(),
            ModelDb.Relic<FabricatorRelic>(), ModelDb.Relic<FlailKnightRelic>(), ModelDb.Relic<FrogKnightRelic>(), ModelDb.Relic<GasBombRelic>(),
            ModelDb.Relic<GlobeHeadRelic>(), ModelDb.Relic<GuardbotRelic>(), ModelDb.Relic<LivingShieldRelic>(), ModelDb.Relic<MagiKnightRelic>(),
            ModelDb.Relic<MysteriousKnightRelic>(), ModelDb.Relic<MyteRelic>(), ModelDb.Relic<NibbitRelic>(), ModelDb.Relic<NoisebotRelic>(),
            ModelDb.Relic<OvicopterRelic>(), ModelDb.Relic<OwlMagistrateRelic>(), ModelDb.Relic<PaelsLegionRelic>(),
            ModelDb.Relic<ScrollOfBitingRelic>(), ModelDb.Relic<SlimedBerserkerRelic>(), ModelDb.Relic<TheForgottenRelic>(), ModelDb.Relic<TheLostRelic>(),
            ModelDb.Relic<TheObscuraRelic>(), ModelDb.Relic<ToadpoleRelic>(), ModelDb.Relic<ToughEggRelic>(), ModelDb.Relic<TrackerRubyRaiderRelic>(),
            ModelDb.Relic<TurretOperatorRelic>(), ModelDb.Relic<ZapbotRelic>()
        ];
    }
}
