namespace NeowCompanions.NeowCompanionsCode;

public enum CompanionKind
{
    None,
    Byrdpip,
    SoulFysh,
    Wriggler,
    CeremonialBeast,
    KinFollower,
    EyeWithTeeth,
    GremlinMerc,
    ThievingHopper,
    Aeonglass,
    LagavulinMatriarch,
    TheKin,
    WaterfallGiant,
    Vantom,
    KnowledgeDemon,
    TheInsatiable,
    Queen,
    TestSubject,
    Seapunk,
    ShrinkerBeetle,
    Operosis,
    Architect,
    Rustclad,
    Shadeleaf,
    Glitchling,
    Bonebinder,
    GildedPage,
    EmberPip,
    FrostPip,
    StormPip,
    ThornPip,
    KaiserCrab,
    BygoneEffigy,
    Byrdonis,
    PhrogParasite,
    SkulkingColony,
    PhantasmalGardener,
    TerrorEel,
    Decimillipede,
    Entomancer,
    InfestedPrism,
    KnightGang,
    MechaKnight,
    SoulNexus,
    AssassinRubyRaider,
    AxeRubyRaider,
    BruteRubyRaider,
    CrossbowRubyRaider,
    Flyconid,
    Fogmog,
    Mawler,
    FuzzyWurmCrawler,
    Inklet,
    SnappingJaxfruit,
    SlitheringStrangler,
    LeafSlimeS,
    LeafSlimeM,
    TwigSlimeS,
    TwigSlimeM,
    VineShambler,
    Chomper,
    CubexConstruct,
    DampCultist,
    CalcifiedCultist,
    CorpseSlug,
    TwoTailedRat,
    SewerClam,
    HauntedShip,
    SludgeSpinner,
    PunchConstruct,
    FossilStalker,
    LivingFog,
    Parafright,
    Tunneler,
    SpinyToad,
    Stabbot,
    HunterKiller,
    TorchHeadAmalgam,
    BowlbugEgg,
    BowlbugNectar,
    BowlbugRock,
    BowlbugSilk,
    LouseProgenitor,
    SlumberingBeetle,
    Axebot, BattleFriendV1, BattleFriendV2, BattleFriendV3, Crusher,
    DevotedSculptor, Exoskeleton, Fabricator, FlailKnight, FrogKnight, GasBomb,
    GlobeHead, Guardbot, LivingShield, MagiKnight, MysteriousKnight, Myte, Nibbit,
    Noisebot, Ovicopter, OwlMagistrate, PaelsLegion, Rocket, ScrollOfBiting,
    SlimedBerserker, TheForgotten, TheLost, TheObscura, Toadpole, ToughEgg,
    TrackerRubyRaider, TurretOperator, Zapbot
}

public static class CompanionState
{
    public static CompanionKind SelectedCompanion { get; set; } = CompanionKind.None;
}
